# Generated by Django 3.1.3 on 2020-11-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenum',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
