# Generated by Django 3.1.3 on 2020-11-27 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '全国的市的信息',
                'verbose_name_plural': '全国的市的信息',
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '全国的省的信息',
                'verbose_name_plural': '全国的省的信息',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.city')),
            ],
            options={
                'verbose_name': '车站的信息',
                'verbose_name_plural': '车站的信息',
            },
        ),
        migrations.CreateModel(
            name='TrainLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainnum', models.CharField(max_length=16)),
                ('starttime', models.DateTimeField()),
                ('startplaceseq', models.IntegerField()),
                ('endtime', models.DateTimeField()),
                ('endplaceseq', models.IntegerField()),
                ('endplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineendplace', to='ticket.station')),
                ('startplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linestartplace', to='ticket.station')),
            ],
            options={
                'verbose_name': '路线的信息',
                'verbose_name_plural': '路线的信息',
            },
        ),
        migrations.CreateModel(
            name='TicketKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('num', models.IntegerField(default=-1)),
                ('price', models.FloatField(default=0)),
                ('endplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kindendplace', to='ticket.station')),
                ('startplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kindstartplace', to='ticket.station')),
            ],
            options={
                'verbose_name': '车票的信息',
                'verbose_name_plural': '车票的信息',
            },
        ),
        migrations.CreateModel(
            name='SingleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('seq', models.IntegerField()),
                ('endplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singleendplace', to='ticket.station')),
                ('startplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singlestartplace', to='ticket.station')),
                ('trainline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.trainline')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.provinces'),
        ),
    ]
