# Generated by Django 3.1.3 on 2020-11-29 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20201129_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketkind',
            name='trainline',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='kindtrainline', to='ticket.trainline'),
            preserve_default=False,
        ),
    ]
